# agents/extraction_agent/ollama_extraction.py
"""
Generic hybrid financial extraction.

Ollama may classify row labels, but it is NEVER trusted to invent
or return financial numbers. Python extracts numbers from actual
financial rows.
"""

import json
import re
from typing import Any, Dict, Optional

import ollama


MODEL = "llama3.2:latest"


def _extract_json(text: str) -> Optional[Dict[str, Any]]:
    if not text:
        return None

    text = text.strip()
    text = re.sub(r"^```json\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"^```\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    try:
        result = json.loads(text)
        return result if isinstance(result, dict) else None
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        try:
            result = json.loads(match.group(0))
            return result if isinstance(result, dict) else None
        except json.JSONDecodeError:
            pass

    return None


NUMBER_PATTERN = re.compile(
    r"""
    \(?\s*
    -?
    (?:
        \d{1,3}(?:,\d{3})+
        |
        \d+
    )
    (?:\.\d+)?
    \s*
    \)?
    """,
    re.VERBOSE,
)


def _parse_number(raw: str) -> Optional[float]:
    if not raw:
        return None

    value = raw.strip()
    negative = value.startswith("(") or value.startswith("-")

    value = (
        value.replace(",", "")
        .replace("(", "")
        .replace(")", "")
        .strip()
    )

    try:
        number = float(value)
    except ValueError:
        return None

    # Never interpret a year as a metric.
    if 1900 <= number <= 2100:
        return None

    return -number if negative else number


def _normalize(text: str) -> str:
    if not text:
        return ""

    text = text.replace("\u00a0", " ")
    text = text.replace("\u200b", "")
    text = re.sub(r"[ \t]+", " ", text)
    return text


# Generic semantic families only.
REVENUE_TERMS = [
    "total revenues",
    "total revenue",
    "net revenues",
    "net revenue",
    "net sales",
    "total sales",
    "revenue",
    "revenues",
    "sales",
    "net sales and revenues",
    "total net sales",
    "sales to customers",
]

NET_PROFIT_TERMS = [
    "net income attributable to common stockholders",
    "net income attributable to shareholders",
    "net income attributable to owners",
    "net income attributable",
    "net income",
    "net earnings",
    "profit for the year",
    "profit for the period",
]

ASSET_TERMS = ["total assets"]

LIABILITY_TERMS = ["total liabilities"]

CASH_FLOW_TERMS = [
    "net cash provided by operating activities",
    "net cash provided by operations",
    "net cash from operating activities",
    "net cash generated from operating activities",
    "net cash generated by operating activities",
    "cash provided by operating activities",
    "cash generated from operating activities",
]

EPS_TERMS = [
    "earnings per common share, diluted",
    "diluted earnings per share",
    "diluted net income per share",
    "net earnings per share",
    "net income per share",
    "earnings per share",
]


def _values_immediately_after(
    text: str,
    position: int,
    max_chars: int = 100,
) -> list[float]:
    """
    Extract consecutive financial values immediately following
    a financial statement row label.

    Designed for rows such as:

        Total assets 624,894 818,042

        Net income 30,425 59,248 77,670

    The parser stops when it encounters substantial prose.
    """

    candidate = text[
        position:position + max_chars
    ]

    candidate = candidate.lstrip(
        " \t|-–—"
    )

    # Remove an optional currency symbol.
    candidate = re.sub(
        r"^(?:\$|₹|Rs\.?)\s*",
        "",
        candidate,
        flags=re.IGNORECASE,
    )

    values = []

    cursor = 0

    while cursor < len(candidate):

        # Skip ordinary whitespace.
        while (
            cursor < len(candidate)
            and candidate[cursor].isspace()
        ):
            cursor += 1

        # Optional currency symbol before each value.
        currency = re.match(
            r"(?:\$|₹|Rs\.?)\s*",
            candidate[cursor:],
            re.IGNORECASE,
        )

        if currency:
            cursor += currency.end()

        match = re.match(
            r"\(?-?(?:\d{1,3}(?:,\d{3})+|\d+)"
            r"(?:\.\d+)?\)?",
            candidate[cursor:],
        )

        if not match:
            break

        value = _parse_number(
            match.group(0)
        )

        if value is None:
            break

        values.append(value)

        cursor += match.end()

        if len(values) >= 3:
            break

        # Look ahead at the text between this value and
        # the next possible value.
        remaining = candidate[cursor:]

        next_number = re.search(
            r"\(?-?(?:\d{1,3}(?:,\d{3})+|\d+)"
            r"(?:\.\d+)?\)?",
            remaining,
        )

        if not next_number:
            break

        separator = remaining[
            :next_number.start()
        ]

        # If substantial alphabetic prose appears before
        # the next number, this is no longer the same row.
        letters = re.sub(
            r"[\s:;,\-–—|$₹.]",
            "",
            separator,
        )

        if len(letters) > 3:
            break

        cursor += next_number.start()

    return values


def _find_row_values(
    section: str,
    terms: list[str],
    max_chars: int = 100,
) -> Optional[list[float]]:
    section = _normalize(section)
    candidates = []

    for term in terms:
        pattern = re.compile(
            re.escape(term).replace(r"\ ", r"\s*"),
            re.IGNORECASE,
        )

        for match in pattern.finditer(section):
            values = _values_immediately_after(
                section,
                match.end(),
                max_chars,
            )

            if not values:
                continue

            # Prefer more specific labels and earlier table rows.
            specificity = len(term.split())
            score = specificity * 10

            candidates.append(
                (score, match.start(), values)
            )

    if not candidates:
        return None

    candidates.sort(
        key=lambda item: (item[0], -item[1]),
        reverse=True,
    )

    return candidates[0][2]


# ---------------------------------------------------------
# Latest fiscal-year value selection
# ---------------------------------------------------------

def _latest_value(
    section: str,
    values: list[float],
) -> Optional[float]:
    """
    Return the value belonging to the latest fiscal year.

    Financial statements are NOT guaranteed to list years
    in descending order.

    Examples:

        2025 2024 2023
        100  90   80
        -> 100

        2023 2024 2025
        80   90   100
        -> 100

        2024 2025
        90   100
        -> 100

    The function detects the year order from the beginning
    of the financial statement instead of assuming a fixed
    column order.
    """

    if not values:
        return None

    if len(values) == 1:
        return values[0]

    if not section:
        return values[0]

    section = _normalize(section)

    # Financial statement column headers are normally
    # located near the beginning of the selected section.
    header = section[:800]

    years = []

    for match in re.finditer(r"\b(20\d{2})\b", header):
        year = int(match.group(1))

        if year not in years:
            years.append(year)

        if len(years) >= len(values):
            break

    # If the year count does not match the extracted values,
    # fall back safely instead of guessing.
    if len(years) != len(values):
        return values[0]

    latest_year = max(years)
    latest_index = years.index(latest_year)

    if latest_index >= len(values):
        return values[0]

    return values[latest_index]
def _extract_revenue(income: str) -> Optional[float]:
    values = _find_row_values(income, REVENUE_TERMS)

    if not values:
        return None

    return _latest_value(income, values)


def _extract_net_profit(
    income: str,
) -> Optional[float]:
    """
    Extract consolidated net income / net earnings
    for the latest fiscal year.

    Supports generic annual-report terminology such as:

        Net income
        Net earnings
        Net income including noncontrolling interests
        Net earnings including noncontrolling interests

    The latest fiscal-year column is selected automatically.
    """

    if not income:
        return None

    income = _normalize(income)

    labels = [
        "net income including noncontrolling interests",
        "net earnings including noncontrolling interests",
        "net income",
        "net earnings",
    ]

    candidates = []

    for label in labels:

        pattern = re.compile(
            re.escape(label).replace(
                r"\ ",
                r"\s+",
            ),
            re.IGNORECASE,
        )

        for match in pattern.finditer(income):

            values = _values_immediately_after(
                income,
                match.end(),
                max_chars=120,
            )

            if values:
                candidates.append(
                    (
                        len(label.split()),
                        match.start(),
                        values,
                    )
                )

    if not candidates:
        return None

    # Prefer the most specific label.
    candidates.sort(
        key=lambda item: (
            item[0],
            -item[1],
        ),
        reverse=True,
    )

    values = candidates[0][2]

    return _latest_value(
        income,
        values,
    )


def _extract_assets(balance: str) -> Optional[float]:
    values = _find_row_values(balance, ASSET_TERMS)

    if not values:
        return None

    return _latest_value(balance, values)


def _extract_liabilities(
    balance: str,
) -> Optional[float]:
    """
    Extract total liabilities from a balance sheet.

    Generic strategies:

    1. Direct:
       Total liabilities 123,456 120,000

    2. Total liabilities and equity:
       Total liabilities and stockholders' equity
       818,042 624,894

       Total stockholders' equity
       411,065 285,970

       Liabilities = Total liabilities and equity
                     - Total stockholders' equity

    3. Extended balance-sheet presentation:
       Total liabilities, redeemable noncontrolling interest,
       and shareholders' equity
       260,823 252,399

       Total shareholders' equity
       97,421 90,349

       Redeemable noncontrolling interest
       271 222

       Liabilities =
           Total assets
           - Total shareholders' equity
           - Redeemable noncontrolling interest

    The latest fiscal-year column is selected automatically.
    """

    if not balance:
        return None

    balance = _normalize(balance)

    # ---------------------------------------------------------
    # Strategy 1: Exact direct "Total liabilities" row.
    #
    # IMPORTANT:
    # Do not treat:
    #
    #   Total liabilities, redeemable noncontrolling interest,
    #   and shareholders' equity
    #
    # as a direct liabilities row.
    # ---------------------------------------------------------

    direct_pattern = re.compile(
        r"""
        \btotal\s+liabilities\b
        (?!\s*(?:,|and)\s*
            (?:
                redeemable\s+noncontrolling\s+interest(?:s)?
                |
                stockholders['’]?\s+equity
                |
                shareholders['’]?\s+equity
                |
                equity
            )
        )
        """,
        re.IGNORECASE | re.VERBOSE,
    )

    direct_candidates = []

    for match in direct_pattern.finditer(balance):

        values = _values_immediately_after(
            balance,
            match.end(),
            max_chars=100,
        )

        if values:
            direct_candidates.append(
                (
                    match.start(),
                    values,
                )
            )

    if direct_candidates:

        # Prefer the first valid direct balance-sheet row.
        direct_candidates.sort(
            key=lambda item: item[0]
        )

        return _latest_value(
            balance,
            direct_candidates[0][1],
        )

    # ---------------------------------------------------------
    # Strategy 2:
    #
    # Total liabilities and stockholders'/shareholders' equity
    # minus
    # Total stockholders'/shareholders' equity
    # ---------------------------------------------------------

    total_equity_values = _find_row_values(
        balance,
        [
            "total stockholders' equity",
            "total stockholders equity",
            "total shareholders' equity",
            "total shareholders equity",
            "total equity",
        ],
    )

    total_liabilities_equity_values = _find_row_values(
        balance,
        [
            "total liabilities and stockholders' equity",
            "total liabilities and stockholders equity",
            "total liabilities and shareholders' equity",
            "total liabilities and shareholders equity",
            "total liabilities and equity",
        ],
    )

    if (
        total_equity_values
        and total_liabilities_equity_values
    ):
        total_equity = _latest_value(
            balance,
            total_equity_values,
        )

        total_liabilities_equity = _latest_value(
            balance,
            total_liabilities_equity_values,
        )

        if (
            total_equity is not None
            and total_liabilities_equity is not None
        ):
            return (
                total_liabilities_equity
                - total_equity
            )

    # ---------------------------------------------------------
    # Strategy 3:
    #
    # Extended balance sheet:
    #
    # Total assets
    # - Total shareholders' equity
    # - Redeemable noncontrolling interest
    #
    # This handles statements such as:
    #
    # Total liabilities, redeemable noncontrolling interest,
    # and shareholders' equity
    #
    # where the report does not provide a standalone
    # "Total liabilities" row.
    # ---------------------------------------------------------

    total_assets_values = _find_row_values(
        balance,
        [
            "total assets",
        ],
    )

    redeemable_nci_values = _find_row_values(
        balance,
        [
            "redeemable noncontrolling interest",
            "redeemable noncontrolling interests",
        ],
    )

    if (
        total_assets_values
        and total_equity_values
    ):
        total_assets = _latest_value(
            balance,
            total_assets_values,
        )

        total_equity = _latest_value(
            balance,
            total_equity_values,
        )

        if (
            total_assets is not None
            and total_equity is not None
        ):

            redeemable_nci = 0.0

            if redeemable_nci_values:
                latest_nci = _latest_value(
                    balance,
                    redeemable_nci_values,
                )

                if latest_nci is not None:
                    redeemable_nci = latest_nci

            liabilities = (
                total_assets
                - total_equity
                - redeemable_nci
            )

            return liabilities

    return None


def _extract_cash_flow(
    cash_flow: str,
) -> Optional[float]:
    """
    Extract net operating cash flow for the latest fiscal year.

    Supports generic financial-report variations such as:

        Net cash provided by operating activities
        Net cash provided by (used in) operating activities
        Net cash flows from operating activities
        Net cash generated by operating activities
        Net cash provided by operations
        Net cash provided by (used in) operations
    """

    if not cash_flow:
        return None

    cash_flow = _normalize(cash_flow)

    labels = [
        r"""
        net\s+cash\s+
        (?:
            provided\s+by
            |
            generated\s+by
            |
            generated\s+from
            |
            flows?\s+from
        )
        \s*
        (?:\(\s*used\s+in\s*\))?
        \s+
        operating\s+activities
        """,

        r"""
        net\s+cash\s+
        (?:
            provided\s+by
            |
            generated\s+by
            |
            generated\s+from
            |
            flows?\s+from
        )
        \s*
        (?:\(\s*used\s+in\s*\))?
        \s+
        operations
        """,

        r"""
        cash\s+
        (?:
            provided\s+by
            |
            generated\s+by
            |
            generated\s+from
            |
            flows?\s+from
        )
        \s*
        (?:\(\s*used\s+in\s*\))?
        \s+
        operating\s+activities
        """,
    ]

    candidates = []

    for label in labels:

        pattern = re.compile(
            label,
            re.IGNORECASE | re.VERBOSE,
        )

        for match in pattern.finditer(cash_flow):

            values = _values_immediately_after(
                cash_flow,
                match.end(),
                max_chars=120,
            )

            if not values:
                continue

            candidates.append(
                (
                    len(
                        re.findall(
                            r"\w+",
                            label,
                        )
                    ),
                    match.start(),
                    values,
                )
            )

    if not candidates:
        return None

    candidates.sort(
        key=lambda item: (
            item[0],
            -item[1],
        ),
        reverse=True,
    )

    return _latest_value(
        cash_flow,
        candidates[0][2],
    )

def _extract_eps(
    income: str,
) -> Optional[float]:
    """
    Extract diluted EPS for the latest fiscal year.

    Generic support for variations including:

        Earnings per share, diluted

        Earnings per common share, diluted

        Net earnings per share - diluted

        Net income per share of common stock ... diluted

        Net income attributable to ... per common share ...
        diluted

        Diluted net income per common share attributable to ...

        Continuing operations - diluted

        Total net earnings per share - diluted
    """

    if not income:
        return None

    income = _normalize(income)

    patterns = [

        # -----------------------------------------------------
        # 1. Standard:
        #
        # Earnings per share ... diluted
        # Earnings per common share ... diluted
        # -----------------------------------------------------

        r"""
        earnings\s+
        per\s+
        (?:common\s+)?
        share
        .*?
        diluted
        """,

        # -----------------------------------------------------
        # 2. Net income / net earnings:
        #
        # Net income per share ... diluted
        # Net earnings per share ... diluted
        # -----------------------------------------------------

        r"""
        net\s+
        (?:income|earnings)
        .*?
        per\s+
        (?:common\s+)?
        share
        .*?
        diluted
        """,

        # -----------------------------------------------------
        # 3. Existing common-stock form:
        #
        # Net income per share of common stock attributable
        # to common stockholders ... Diluted
        # -----------------------------------------------------

        r"""
        net\s+
        income\s+
        per\s+
        share
        .*?
        common\s+
        stock
        .*?
        diluted
        """,

        # -----------------------------------------------------
        # 4. NEW generic form:
        #
        # Diluted net income per common share attributable
        # to Walmart
        #
        # Also works for:
        #
        # Diluted net income per common share
        # Diluted net earnings per common share
        # -----------------------------------------------------

       r"""
diluted
\s+
net
\s+
(?:income|earnings)
\s+
per
\s+
(?:common\s+)?
share
(?:\s+
    attributable
    \s+
    to
    .*?
)?
(?=
    \s*
    (?:\$|₹|Rs\.?)?
    \s*
    \(?
    -?
    \d
)
""",
        # -----------------------------------------------------
        # 5. Continuing operations - diluted
        # -----------------------------------------------------

        r"""
        continuing\s+
        operations
        \s*[-–—:]
        \s*
        diluted
        """,

        # -----------------------------------------------------
        # 6. Generic diluted earnings per share
        # -----------------------------------------------------

        r"""
        diluted
        \s+
        earnings
        \s+
        per
        \s+
        share
        """,
    ]

    candidates = []

    for pattern_text in patterns:

        pattern = re.compile(
            pattern_text,
            re.IGNORECASE | re.VERBOSE,
        )

        for match in pattern.finditer(income):

            values = _values_immediately_after(
                income,
                match.end(),
                max_chars=150,
            )

            if not values:
                continue

            # EPS values are normally small decimal numbers.
            # Reject obvious share counts such as:
            #
            # 3,528
            # 10,827
            #
            eps_values = [
                value
                for value in values
                if -100.0 < value < 100.0
            ]

            if not eps_values:
                continue

            candidates.append(
                (
                    len(
                        re.findall(
                            r"\w+",
                            pattern_text,
                        )
                    ),
                    match.start(),
                    eps_values,
                )
            )

    if not candidates:
        return None

    candidates.sort(
        key=lambda item: (
            item[0],
            -item[1],
        ),
        reverse=True,
    )

    return _latest_value(
        income,
        candidates[0][2],
    )


def extract_numbers_from_sections(
    sections: Dict[str, str],
) -> Dict[str, Any]:
    """
    Deterministic extraction from the selected financial statements only.
    """

    income = sections.get("income_statement", "")
    balance = sections.get("balance_sheet", "")
    cash_flow = sections.get("cash_flow", "")

    return {
        "revenue": _extract_revenue(income),
        "net_profit": _extract_net_profit(income),
        "assets": _extract_assets(balance),
        "liabilities": _extract_liabilities(balance),
        "cash_flow": _extract_cash_flow(cash_flow),
        "eps": _extract_eps(income),
    }


def extract_first_financial_number(
    row: Optional[str],
) -> Optional[float]:
    if not row:
        return None

    for match in NUMBER_PATTERN.finditer(row):
        value = _parse_number(match.group(0))
        if value is not None:
            return value

    return None


def extract_numbers_from_rows(
    rows: Dict[str, Any],
) -> Dict[str, Any]:
    return {
        "revenue": extract_first_financial_number(
            rows.get("revenue_row")
        ),
        "net_profit": extract_first_financial_number(
            rows.get("net_profit_row")
        ),
        "assets": extract_first_financial_number(
            rows.get("total_assets_row")
        ),
        "liabilities": extract_first_financial_number(
            rows.get("total_liabilities_row")
        ),
        "cash_flow": extract_first_financial_number(
            rows.get("operating_cash_flow_row")
        ),
        "eps": extract_first_financial_number(
            rows.get("eps_row")
        ),
    }


def identify_financial_rows(
    document_text: str,
) -> Dict[str, Any]:
    """
    Ollama is used only for semantic row-label classification.
    It is not trusted for numeric extraction.
    """

    if not document_text:
        raise ValueError("Financial statement context is empty.")

    prompt = f"""
You are a financial-statement row classifier.

Identify the actual row label for each requested metric from the
financial statements below.

Return ONLY JSON:
{{
  "revenue_label": null,
  "net_profit_label": null,
  "total_assets_label": null,
  "total_liabilities_label": null,
  "operating_cash_flow_label": null,
  "eps_label": null
}}

Rules:
- Use only labels that actually occur in the supplied statements.
- Do not invent company names or labels.
- Revenue may be revenue, net revenue, net sales, sales, total revenue, etc.
- Profit may be net income, net earnings, profit for the period/year, etc.
- Assets = total assets.
- Liabilities = total liabilities.
- Operating cash flow = the row giving net cash from/provided by/generated
  from operating activities.
- EPS = diluted earnings/net-income/net-earnings per share where available.
- Return labels only. Never return numbers.
- Return JSON only.

FINANCIAL STATEMENTS:
{document_text}
"""

    response = ollama.chat(
        model=MODEL,
        messages=[
            {
                "role": "system",
                "content": "Return JSON only. Never explain.",
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
        format="json",
        options={
            "temperature": 0,
            "num_predict": 500,
        },
    )

    result = _extract_json(
        response["message"]["content"]
    )

    if result is None:
        raise ValueError("Ollama did not return valid JSON.")

    return {
        "revenue_label": result.get("revenue_label"),
        "net_profit_label": result.get("net_profit_label"),
        "total_assets_label": result.get("total_assets_label"),
        "total_liabilities_label": result.get("total_liabilities_label"),
        "operating_cash_flow_label": result.get("operating_cash_flow_label"),
        "eps_label": result.get("eps_label"),
    }


def extract_with_ollama(
    document_text: str,
) -> Dict[str, Any]:
    """
    Complete generic pipeline:
      1. locate financial statements
      2. optionally classify row labels with Ollama
      3. deterministically extract numbers
      4. return metrics

    Numeric values NEVER come from Ollama.
    """

    from agents.extraction_agent.financial_section_selector import (
        build_extraction_context,
        extract_financial_sections,
    )

    if not document_text:
        raise ValueError("Document text is empty.")

    sections = extract_financial_sections(
        document_text
    )

    if not any(sections.values()):
        raise ValueError(
            "No financial statement sections were found."
        )

    context = build_extraction_context(
        document_text
    )

    # Ollama labels are retained for traceability, but extraction remains
    # deterministic so model wording cannot produce incorrect numbers.
    try:
        labels = identify_financial_rows(context)
    except Exception:
        labels = {
            "revenue_label": None,
            "net_profit_label": None,
            "total_assets_label": None,
            "total_liabilities_label": None,
            "operating_cash_flow_label": None,
            "eps_label": None,
        }

    rows = {
        "revenue_row": labels.get("revenue_label"),
        "net_profit_row": labels.get("net_profit_label"),
        "total_assets_row": labels.get("total_assets_label"),
        "total_liabilities_row": labels.get("total_liabilities_label"),
        "operating_cash_flow_row": labels.get(
            "operating_cash_flow_label"
        ),
        "eps_row": labels.get("eps_label"),
    }

    metrics = extract_numbers_from_sections(
        sections
    )

    return {
        "model": MODEL,
        "rows": rows,
        "metrics": metrics,
    }
